CREATE TABLE visits (
    id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    petId INTEGER NOT NULL,
    vetId INTEGER NOT NULL,
    appointment DATETIME NOT NULL,
    created DATETIME NOT NULL,
    CONSTRAINT FK_visits_pets_petId FOREIGN KEY (petId) REFERENCES pets(id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_visits_vets_vetId FOREIGN KEY (vetId) REFERENCES vets(id) ON DELETE CASCADE ON UPDATE CASCADE
);